spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/updates.xml
    
postgres:
  store-type: database